package com.github.parasmani300.avroformatexample.avro;

/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SampleClass extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = 6150981699832178266L;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SampleClass\",\"namespace\":\"com.github.parasmani300.avroformatexample.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"age\",\"type\":\"string\"}]}");
    public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

    private static SpecificData MODEL$ = new SpecificData();

    private static final BinaryMessageEncoder<SampleClass> ENCODER =
            new BinaryMessageEncoder<SampleClass>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<SampleClass> DECODER =
            new BinaryMessageDecoder<SampleClass>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     */
    public static BinaryMessageDecoder<SampleClass> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     */
    public static BinaryMessageDecoder<SampleClass> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<SampleClass>(MODEL$, SCHEMA$, resolver);
    }

    /** Serializes this SampleClass to a ByteBuffer. */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /** Deserializes a SampleClass from a ByteBuffer. */
    public static SampleClass fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    @Deprecated public int id;
    @Deprecated public java.lang.CharSequence name;
    @Deprecated public java.lang.CharSequence age;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public SampleClass() {}

    /**
     * All-args constructor.
     * @param id The new value for id
     * @param name The new value for name
     * @param age The new value for age
     */
    public SampleClass(java.lang.Integer id, java.lang.CharSequence name, java.lang.CharSequence age) {
        this.id = id;
        this.name = name;
        this.age = age;
    }

    public org.apache.avro.Schema getSchema() { return SCHEMA$; }
    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0: return id;
            case 1: return name;
            case 2: return age;
            default: throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value="unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0: id = (java.lang.Integer)value$; break;
            case 1: name = (java.lang.CharSequence)value$; break;
            case 2: age = (java.lang.CharSequence)value$; break;
            default: throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    /**
     * Gets the value of the 'id' field.
     * @return The value of the 'id' field.
     */
    public java.lang.Integer getId() {
        return id;
    }

    /**
     * Sets the value of the 'id' field.
     * @param value the value to set.
     */
    public void setId(java.lang.Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the 'name' field.
     * @return The value of the 'name' field.
     */
    public java.lang.CharSequence getName() {
        return name;
    }

    /**
     * Sets the value of the 'name' field.
     * @param value the value to set.
     */
    public void setName(java.lang.CharSequence value) {
        this.name = value;
    }

    /**
     * Gets the value of the 'age' field.
     * @return The value of the 'age' field.
     */
    public java.lang.CharSequence getAge() {
        return age;
    }

    /**
     * Sets the value of the 'age' field.
     * @param value the value to set.
     */
    public void setAge(java.lang.CharSequence value) {
        this.age = value;
    }

    /**
     * Creates a new SampleClass RecordBuilder.
     * @return A new SampleClass RecordBuilder
     */
    public static com.github.parasmani300.avroformatexample.avro.SampleClass.Builder newBuilder() {
        return new com.github.parasmani300.avroformatexample.avro.SampleClass.Builder();
    }

    /**
     * Creates a new SampleClass RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new SampleClass RecordBuilder
     */
    public static com.github.parasmani300.avroformatexample.avro.SampleClass.Builder newBuilder(com.github.parasmani300.avroformatexample.avro.SampleClass.Builder other) {
        return new com.github.parasmani300.avroformatexample.avro.SampleClass.Builder(other);
    }

    /**
     * Creates a new SampleClass RecordBuilder by copying an existing SampleClass instance.
     * @param other The existing instance to copy.
     * @return A new SampleClass RecordBuilder
     */
    public static com.github.parasmani300.avroformatexample.avro.SampleClass.Builder newBuilder(com.github.parasmani300.avroformatexample.avro.SampleClass other) {
        return new com.github.parasmani300.avroformatexample.avro.SampleClass.Builder(other);
    }

    /**
     * RecordBuilder for SampleClass instances.
     */
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SampleClass>
            implements org.apache.avro.data.RecordBuilder<SampleClass> {

        private int id;
        private java.lang.CharSequence name;
        private java.lang.CharSequence age;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(com.github.parasmani300.avroformatexample.avro.SampleClass.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.id)) {
                this.id = data().deepCopy(fields()[0].schema(), other.id);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.name)) {
                this.name = data().deepCopy(fields()[1].schema(), other.name);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.age)) {
                this.age = data().deepCopy(fields()[2].schema(), other.age);
                fieldSetFlags()[2] = true;
            }
        }

        /**
         * Creates a Builder by copying an existing SampleClass instance
         * @param other The existing instance to copy.
         */
        private Builder(com.github.parasmani300.avroformatexample.avro.SampleClass other) {
            super(SCHEMA$);
            if (isValidValue(fields()[0], other.id)) {
                this.id = data().deepCopy(fields()[0].schema(), other.id);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.name)) {
                this.name = data().deepCopy(fields()[1].schema(), other.name);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.age)) {
                this.age = data().deepCopy(fields()[2].schema(), other.age);
                fieldSetFlags()[2] = true;
            }
        }

        /**
         * Gets the value of the 'id' field.
         * @return The value.
         */
        public java.lang.Integer getId() {
            return id;
        }

        /**
         * Sets the value of the 'id' field.
         * @param value The value of 'id'.
         * @return This builder.
         */
        public com.github.parasmani300.avroformatexample.avro.SampleClass.Builder setId(int value) {
            validate(fields()[0], value);
            this.id = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'id' field has been set.
         * @return True if the 'id' field has been set, false otherwise.
         */
        public boolean hasId() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'id' field.
         * @return This builder.
         */
        public com.github.parasmani300.avroformatexample.avro.SampleClass.Builder clearId() {
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'name' field.
         * @return The value.
         */
        public java.lang.CharSequence getName() {
            return name;
        }

        /**
         * Sets the value of the 'name' field.
         * @param value The value of 'name'.
         * @return This builder.
         */
        public com.github.parasmani300.avroformatexample.avro.SampleClass.Builder setName(java.lang.CharSequence value) {
            validate(fields()[1], value);
            this.name = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'name' field has been set.
         * @return True if the 'name' field has been set, false otherwise.
         */
        public boolean hasName() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'name' field.
         * @return This builder.
         */
        public com.github.parasmani300.avroformatexample.avro.SampleClass.Builder clearName() {
            name = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        /**
         * Gets the value of the 'age' field.
         * @return The value.
         */
        public java.lang.CharSequence getAge() {
            return age;
        }

        /**
         * Sets the value of the 'age' field.
         * @param value The value of 'age'.
         * @return This builder.
         */
        public com.github.parasmani300.avroformatexample.avro.SampleClass.Builder setAge(java.lang.CharSequence value) {
            validate(fields()[2], value);
            this.age = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        /**
         * Checks whether the 'age' field has been set.
         * @return True if the 'age' field has been set, false otherwise.
         */
        public boolean hasAge() {
            return fieldSetFlags()[2];
        }


        /**
         * Clears the value of the 'age' field.
         * @return This builder.
         */
        public com.github.parasmani300.avroformatexample.avro.SampleClass.Builder clearAge() {
            age = null;
            fieldSetFlags()[2] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public SampleClass build() {
            try {
                SampleClass record = new SampleClass();
                record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
                record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
                record.age = fieldSetFlags()[2] ? this.age : (java.lang.CharSequence) defaultValue(fields()[2]);
                return record;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<SampleClass>
            WRITER$ = (org.apache.avro.io.DatumWriter<SampleClass>)MODEL$.createDatumWriter(SCHEMA$);

    @Override public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<SampleClass>
            READER$ = (org.apache.avro.io.DatumReader<SampleClass>)MODEL$.createDatumReader(SCHEMA$);

    @Override public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

}
